name: Publish (Release)

on:
  release:
    types:
      - published

jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [latest, alpine, 2.5, 2.5-alpine, 2.5.5, 2.5.5-alpine, 2.6, 2.6-alpine, 2.6.2, 2.6.2-alpine, 2.6.7, 2.6.7-alpine, 2.7, 2.7-alpine, 2.7.1, 2.7.1-alpine]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Modify Dockerfile
        run: |
          sed -i -e "s|%VERSION%|${{ matrix.tag }}|g" Dockerfile
      - name: Build and push
        id: docker_build_master
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/snorwin/haproxy:${{ matrix.tag }}
          platforms: linux/amd64
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
            HASH=${{ github.sha }}
